doc-valid-idents = [
  "Homebrew",
  "SQLite",
  "JSON",
  "TOML",
  "CLI",
  "API",
  "HTTP",
  "HTTPS",
  "URL",
  "UUID",
  "SHA256",
  "CVE",
  "macOS",
  "PyPI",
  "npm",
  "Cargo",
  "Rust",
  "GitHub",
  "CI",
  "CD",
  "SSL",
  "TLS",
  "TCP",
  "UDP",
  "DNS",
  "POSIX",
  "UTF",
  "ASCII",
  ".." # Include the defaults
]

# Disallow direct filesystem operations - force everything through our own abstraction
disallowed-types = [
  "std::fs::DirEntry",
  "std::fs::File",
  "std::fs::OpenOptions",
  "std::fs::ReadDir",
  "tokio::fs::DirBuilder",
  "tokio::fs::DirEntry",
  "tokio::fs::File",
  "tokio::fs::OpenOptions",
  "tokio::fs::ReadDir",
]

disallowed-methods = [
  "std::fs::canonicalize",
  "std::fs::copy",
  "std::fs::create_dir",
  "std::fs::create_dir_all",
  "std::fs::hard_link",
  "std::fs::metadata",
  "std::fs::read",
  "std::fs::read_dir",
  "std::fs::read_link",
  "std::fs::read_to_string",
  "std::fs::remove_dir",
  "std::fs::remove_dir_all",
  "std::fs::remove_file",
  "std::fs::rename",
  "std::fs::set_permissions",
  "std::fs::soft_link",
  "std::fs::symlink_metadata",
  "std::fs::write",

  "tokio::fs::canonicalize",
  "tokio::fs::copy",
  "tokio::fs::create_dir",
  "tokio::fs::create_dir_all",
  "tokio::fs::hard_link",
  "tokio::fs::metadata",
  "tokio::fs::read",
  "tokio::fs::read_dir",
  "tokio::fs::read_link",
  "tokio::fs::read_to_string",
  "tokio::fs::remove_dir",
  "tokio::fs::remove_dir_all",
  "tokio::fs::remove_file",
  "tokio::fs::rename",
  "tokio::fs::set_permissions",
  "tokio::fs::symlink_metadata",
  "tokio::fs::try_exists",
  "tokio::fs::write",

  # Disallow direct process spawning - should go through fastbrew::process for logging
  "std::process::Command::new",
  "std::process::Command::spawn",
  "std::process::Command::output",
  "std::process::Command::status",
  "tokio::process::Command::new",
  "tokio::process::Command::spawn",
  "tokio::process::Command::output",
  "tokio::process::Command::status",

  # Network operations should go through fastbrew::http for progress tracking
  "std::net::TcpStream::connect",
  "tokio::net::TcpStream::connect",
]
