[package]
name = "fastbrew"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { workspace = true, features = ["derive", "string", "wrap_help"] }
fastbrew-cli = { workspace = true }
fastbrew-static = { workspace = true }
